Repository ucsb-cs156-s22/s22-4pm-courses, pull requests merged in 2022-06, with the labels that each got.

#32 s22-4pm-02 Created Placeholder Page for Personal Schedule Details
  .github/workflows/34-frontend-mutation-testing.yml
  frontend/src/App.js
  frontend/src/main/components/PersonalSchedules/PersonalSchedulesTable.js
  frontend/src/main/pages/PersonalSchedules/PersonalSchedulesDetailsPage.js
  frontend/src/tests/components/PersonalSchedules/PersonalSchedulesTable.test.js
  frontend/src/tests/pages/PersonalSchedules/PersonalSchedulesDetailsPage.test.js
Labels: s22-4pm-2, Merge Candidate, :gear: Deploying-on-QA

#41 s22-4pm-2 ml - added course controllers and tests
  src/main/java/edu/ucsb/cs156/courses/controllers/ApiController.java
  src/main/java/edu/ucsb/cs156/courses/controllers/CoursesController.java
  src/main/java/edu/ucsb/cs156/courses/entities/Courses.java
  src/main/java/edu/ucsb/cs156/courses/errors/BadEnrollCdException.java
  src/main/java/edu/ucsb/cs156/courses/repositories/CoursesRepository.java
  src/test/java/edu/ucsb/cs156/courses/controllers/CoursesControllerTests.java
Labels: s22-4pm-2, :gear: Deploying-on-QA

#51 s22-4pm-02: ss - added placeholder page for personal schedules edit
  frontend/src/App.js
Labels: s22-4pm-2, :hourglass: Waiting on CI/CD to Merge

#50 s22-4pm-1 Section Table redesign
  frontend/src/fixtures/sectionFixtures.js
  frontend/src/main/components/Sections/SectionsTable.js
  frontend/src/main/components/SectionsTableBase.js
  frontend/src/main/utils/sectionUtils.js
  frontend/src/main/utils/timeUtils.js
  frontend/src/tests/components/Sections/SectionsTable.test.js
  frontend/src/tests/components/SectionsTableBase.test.js
  frontend/src/tests/utils/sectionUtils.test.js
  frontend/src/tests/utils/timeUtils.test.js
  src/main/java/edu/ucsb/cs156/courses/documents/CoursePage.java
  src/test/java/edu/ucsb/cs156/courses/documents/CoursePageFixtures.java
Labels: s22-4pm-1, :interrobang: FIXME-respond-to-cr

#54 s22-4pm-2 ml - added course fixtures, form, table, create page, and index page and tests
  frontend/src/App.js
  frontend/src/fixtures/coursesFixtures.js
  frontend/src/main/components/Courses/CourseForm.js
  frontend/src/main/components/Courses/CourseTable.js
  frontend/src/main/components/Nav/AppNavbar.js
  frontend/src/main/components/PersonalSchedules/PersonalSchedulesTable.js
  frontend/src/main/pages/Courses/CoursesCreatePage.js
  frontend/src/main/pages/Courses/CoursesIndexPage.js
  frontend/src/main/utils/CoursesUtils.js
  frontend/src/tests/components/Courses/CourseForm.test.js
  frontend/src/tests/components/Courses/CourseTable.test.js
  frontend/src/tests/components/Nav/AppNavbar.test.js
  frontend/src/tests/pages/Courses/CoursesCreatePage.test.js
  frontend/src/tests/pages/Courses/CoursesIndexPage.test.js
  frontend/src/tests/utils/CoursesUtils.test.js
  frontend/stryker.conf.json
Labels: s22-4pm-2, :hourglass: Waiting on CI/CD to Merge

#56 s22-4pm-1 Added favicon, navbar icon, and footer copyright info
  frontend/public/index.html
  frontend/public/tower-favicon.ico
  frontend/src/assets/header-logo-240.png
  frontend/src/main/components/Nav/AppNavbar.js
  frontend/src/main/components/Nav/Footer.js
  frontend/src/tests/components/Nav/AppNavbar.test.js
  frontend/src/tests/components/Nav/Footer.test.js
Labels: s22-4pm-1

#64 ml - added personal schedule edit page back
  frontend/src/App.js
Labels: s22-4pm-2

#61 4pm-2 - kt - psid sections endpoint
  src/main/java/edu/ucsb/cs156/courses/controllers/PersonalSectionsController.java
  src/main/java/edu/ucsb/cs156/courses/services/UCSBCurriculumService.java
  src/test/java/edu/ucsb/cs156/courses/controllers/PersonalSectionsControllerTests.java
  src/test/java/edu/ucsb/cs156/courses/documents/PersonalSectionsFixtures.java
  src/test/java/edu/ucsb/cs156/courses/services/UCSBCurriculumServiceTests.java
Labels: s22-4pm-2, 10, :hourglass: Waiting on CI/CD to Merge

#65 s22-4pm-2 ml - changed naming issue
  frontend/src/App.js
  frontend/src/fixtures/pscourseFixtures.js
  frontend/src/main/components/Nav/AppNavbar.js
  frontend/src/main/pages/Courses/PSCourseCreatePage.js
  frontend/src/main/pages/Courses/PSCourseIndexPage.js
  frontend/src/tests/components/Courses/CourseForm.test.js
  frontend/src/tests/components/Courses/CourseTable.test.js
  frontend/src/tests/pages/Courses/CoursesCreatePage.test.js
  frontend/src/tests/pages/Courses/CoursesIndexPage.test.js
  src/main/java/edu/ucsb/cs156/courses/controllers/PSCourseController.java
  src/main/java/edu/ucsb/cs156/courses/controllers/PersonalSectionsController.java
  src/main/java/edu/ucsb/cs156/courses/entities/PSCourse.java
  src/main/java/edu/ucsb/cs156/courses/repositories/CoursesRepository.java
  src/main/java/edu/ucsb/cs156/courses/repositories/PSCourseRepository.java
  src/test/java/edu/ucsb/cs156/courses/controllers/PSCourseControllerTests.java
  src/test/java/edu/ucsb/cs156/courses/controllers/PersonalSectionsControllerTests.java
Labels: s22-4pm-2, Merge Candidate, :+1: Peer-CR-done
