Repository ucsb-cs156-s22/s22-4pm-courses, pull requests merged in 2022-05, with the labels that each got.

#12 Added heroku qa link for 4pm-2
  README.md
Labels: s22-4pm-2, FIXME-peer-cr-missing, Merge Candidate

#14 Aviv Samet- added QA heroku links for 4pm-1 to readme
  README.md
Labels: s22-4pm-1, Merge Candidate

#27 4pm02 added heroku dashboard + app link
  README.md
Labels: s22-4pm-2, 10

#29 Section Table and Storybook Component
  frontend/src/fixtures/sectionFixtures.js
  frontend/src/main/components/Sections/SectionsTable.js
  frontend/src/main/utils/sectionUtils.js
  frontend/src/main/utils/timeUtils.js
  frontend/src/stories/components/Sections/SectionTable.stories.js
  frontend/src/tests/components/Sections/SectionsTable.test.js
  frontend/src/tests/utils/sectionUtils.test.js
  frontend/src/tests/utils/timeUtils.test.js
Labels: s22-4pm-1

#24 ml - added entities and repositories for courses
  src/main/java/edu/ucsb/cs156/courses/entities/Courses.java
  src/main/java/edu/ucsb/cs156/courses/repositories/CoursesRepository.java
Labels: s22-4pm-2, Merge Candidate

#30 s22-4pm-1: M medearis Add course section controller
  src/main/java/edu/ucsb/cs156/courses/controllers/UCSBSectionsController.java
  src/main/java/edu/ucsb/cs156/courses/documents/ConvertedSection.java
  src/main/java/edu/ucsb/cs156/courses/documents/Course.java
  src/main/java/edu/ucsb/cs156/courses/documents/CourseInfo.java
  src/main/java/edu/ucsb/cs156/courses/documents/CoursePage.java
  src/main/java/edu/ucsb/cs156/courses/documents/FinalExam.java
  src/main/java/edu/ucsb/cs156/courses/documents/GeneralEducation.java
  src/main/java/edu/ucsb/cs156/courses/documents/Instructor.java
  src/main/java/edu/ucsb/cs156/courses/documents/Section.java
  src/main/java/edu/ucsb/cs156/courses/documents/TimeLocation.java
  src/main/java/edu/ucsb/cs156/courses/entities/PersonalSchedule.java
  src/main/java/edu/ucsb/cs156/courses/entities/UCSBSubject.java
  src/main/java/edu/ucsb/cs156/courses/entities/User.java
  src/main/java/edu/ucsb/cs156/courses/models/CurrentUser.java
  src/main/java/edu/ucsb/cs156/courses/models/SystemInfo.java
  src/main/java/edu/ucsb/cs156/courses/services/UCSBCurriculumService.java
  src/test/java/edu/ucsb/cs156/courses/controllers/UCSBSectionsControllerTests.java
  src/test/java/edu/ucsb/cs156/courses/documents/CoursePageFixtures.java
  src/test/java/edu/ucsb/cs156/courses/documents/CoursePageTests.java
  src/test/java/edu/ucsb/cs156/courses/services/UCSBCurriculumServiceTests.java
Labels: s22-4pm-1, FIXME-peer-cr-missing, Merge Candidate

#33 s22-4pm-2: mh-added updates to appnavbar
  frontend/src/stories/components/Nav/AppNavbar.stories.js
Labels: s22-4pm-2

#35 s22-4pm-1: Suppress error messages for frontend tests
  frontend/src/tests/components/BasicCourseSearch/BasicCourseSearchForm.test.js
  frontend/src/tests/components/Subjects/SingleSubjectDropdown.test.js
  frontend/src/tests/pages/HomePage.test.js
Labels: s22-4pm-1

#36 s22-4pm-2 Endpoint that returns info about a section
  src/main/java/edu/ucsb/cs156/courses/controllers/UCSBSectionsController.java
  src/main/java/edu/ucsb/cs156/courses/services/UCSBCurriculumService.java
  src/test/java/edu/ucsb/cs156/courses/controllers/UCSBSectionsControllerTests.java
  src/test/java/edu/ucsb/cs156/courses/documents/SectionFixtures.java
  src/test/java/edu/ucsb/cs156/courses/services/UCSBCurriculumServiceTests.java
Labels: s22-4pm-2, :interrobang: FIXME-issue?, :+1: Peer-CR-done
